language: node_js
node_js:
- "8"

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - test $TRAVIS_BRANCH = "master" && firebase deploy -P default --token $FIREBASE_DEPLOY_KEY
  - tar cvzf paris-culture-analyse.tar.gz dist/*

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_DEPLOY_KEY
  file: paris-culture-analyse.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: MielPoPSCrew/ParisCultureAnalyze
